version: '2'

services:
  web:
    restart: always
    build: .
    expose:
      - '8012'
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=camberwelldistribution.com,www.camberwelldistribution.com
      - LETSENCRYPT_HOST=camberwelldistribution.com,www.camberwelldistribution.com
      - LETSENCRYPT_EMAIL=info@camberwelldistribution.com
      - LETSENCRYPT_TEST=false

networks:
  proxy:
    external:
      name: proxy
